{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ValidatorSet",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators{chain_name=~\"$chain_name\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Connected validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, sum by (kubernetes_pod_name)(aptos_connections{network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\".*\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(aptos_consensus_last_committed_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Participating Stake %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_voting_power_last_100_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"}/aptos_chain_health_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"})*100"
    }
   ]
  },
  {
   "title": "Participating validator %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_num_validators_last_100_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"}/aptos_chain_health_total_num_validators{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator\"})*100"
    }
   ]
  },
  {
   "title": "Sync lagging validator",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(clamp_min(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\".*\", role=~\"validator\", data_type=\"transactions\"} - on(kubernetes_pod_name,role) aptos_state_sync_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\".*\", role=~\"validator\", type=\"synced\"}, 0) > 50000) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Sync lagging validators",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 2, "y": 6 },
   "targets": [
    {
     "expr": "clamp_min(aptos_data_client_highest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\".*\", role=~\"validator\", data_type=\"transactions\"} - on(kubernetes_pod_name,role) aptos_state_sync_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\".*\", role=~\"validator\", type=\"synced\"}, 0) > 50000"
    }
   ]
  },
  {
   "title": "Not Participating in Consensus",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "aptos_committed_votes_in_window{chain_name=~\"premainnet\", namespace=~\"telemetry-service\", kubernetes_pod_name=~\".*\", role=~\"validator\"} + aptos_committed_proposals_in_window{chain_name=~\"premainnet\", namespace=~\"telemetry-service\", kubernetes_pod_name=~\".*\", role=~\"validator\"} == 0"
    }
   ]
  },
  { "title": "SLA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_last_committed_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Committed user transactions per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_consensus_last_committed_version{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator\"}[1m]) - 2 * rate(aptos_consensus_last_committed_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Validators participating in consensus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, aptos_chain_health_participating_voting_power_last_100_rounds{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator\"} * 100/aptos_chain_health_total_voting_power{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator\"})",
     "legendFormat": "participating stake"
    },
    {
     "expr": "quantile(0.67, aptos_chain_health_participating_num_validators_last_100_rounds{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator\"} * 100/aptos_chain_health_total_num_validators{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"validator\"})",
     "legendFormat": "participating validators"
    }
   ]
  },
  { "title": "Validator health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Validator Connected Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name)(aptos_connections{network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Committed & Synced Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{type=\"committed\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-committed"
    },
    {
     "expr": "aptos_state_sync_version{type=\"synced\", role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-synced"
    }
   ]
  },
  { "title": "Fullnode health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Fullnode Connected Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, network_id)(aptos_connections{role_type=\"full_node\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Fullnode Upstream Peers",
   "type": "graph",
   "description": "Number of upstream validator peers a full node can proxy transactions up to",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_active_upstream_peers{role=\"fullnode\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "State synced version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{type=\"synced\", role=\"fullnode\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "The error rate of main loop.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_error_count{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m]) / on (kubernetes_pod_name) rate(consensus_duration_count{op='main_loop', kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Round Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_consensus_timeout_rounds_count{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Current Round",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "aptos_consensus_current_round{kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Mempool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{index=\"system_ttl\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg e2e latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted|commit_rejected\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])/rate(aptos_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_execute_block_seconds_bucket{role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aptos_executor_execute_block_seconds_bucket{role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_execute_block_seconds_bucket{role=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}